name: todo-list
version: 0.1.0
homepage: null
synopsis: A pure morloc todo list
description: null
category: null
license: MIT
author: null
maintainer: null
github: null
bug-reports: null
dependencies: []
